# Configurations
markdown: kramdown
markdown_ext:  markdown,mkdown,mkdn,mkd,md
highlighter: pygments

# Permalinks
permalink:        /:year/:title

# Setup
title:            'Andy Tran | github.io'
tagline:          'Tech, innovation and global health'
description:      'Portfolio showcasing my work in web development and global health'
url:              'http://xanadhi.github.io/'
baseurl:          ''

# Navigation
navigation:
- text: About
  url: /about/
- text: Resume
  url: /resume/
- text: Blog
  url: /blog/
- text: Tags
  url: /tags/
- text: Archive
  url : /archive/

# Author Details
author:         'Andy Tran'
linkedin:       'https://ca.linkedin.com/pub/andy-tran/1a/80b/485/'
twitter:        'https://twitter.com/andyxtran'
facebook:       'https://www.facebook.com/andyxtran'
gplus:          'https://plus.google.com/+AndyTran88'

# Google Analytics
gahandler: 'UA-39675259-1'

# Disqus
disqushandler: 'testingblogo'

# Blog Configurations
paginate: 10 # Posts per page on the blog index
paginate_path: '/blog/page:num'
destination: ./_site

# Custom vars
version:          0.7.9
